# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# we can configure exactly when and why the pipeline will trigger.
trigger:
- master

# by default, it also will trigger on every PR

# define what kind of computer the build will run on.
pool:
  vmImage: 'ubuntu-latest' # one of Microsoft's Ubuntu VMs.

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- script: dotnet build --configuration Release
  displayName: dotnet build

# i don't really have any tests
# - script: dotnet test
#   displayName: dotnet test

# static analysis with SonarQube
# with static analysis, the source code is analyzed for
# poor coding practices, for code smells
#   technical debt
#   code coverage

# we can do deployment to various places from Azure Pipelines
# Web Deploy
# deploy to various cloud services
